# Используем официальный образ Python как основу
FROM augmentation:latest

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Активируем виртуальное окружение
ENV PATH="/home/appuser/venv/bin:$PATH"

# Запускаем контейнер от обычного пользователя
USER appuser
